version: '3'
services:
  client:
  # image to build the container from
    image: node:18
    container_name: florin_client
  # expose (a) container port(s) to a local/host port
    ports:
      - 8080:8080
  # where is the code, and shall we access it?
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
  # what to do once the container has started
    command: bash -c "npm install && npm run dev"
    depends_on:
      - api

  api:
    image: node:18
    container_name: florin_api
    env_file:
      - .env
    environment:
      - ${DB_URL}
      - ${PORT}
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    

